app:
  monitor.dir: C:\\tmp\input

  kafka:
    admin:
      bootstrap.servers: localhost:9092
    producer:
      batch.size: 524288
      linger.ms: 10
      bootstrap.servers: ${app.kafka.admin.bootstrap.servers}
    topics[TradeRecordProcessed] : trade-records
