app:
  kafka:
    consumer:
      bootstrap.servers: localhost:9092
      max.poll.interval.ms: 300000
    topic: trade-records

---
spring:
  profiles: service-A

app:
  kafka:
    consumer:
      group.id: group1
    idle-between-polls: 300000

  trade-records:
    target-location: C:\\tmp\service-A\
    target-filename: service-A

---
spring:
  profiles: service-B

app:
  kafka:
    consumer:
      group.id: group2
    idle-between-polls: 60000

  trade-records:
    target-location: C:\\tmp\service-B\
    target-filename: service-B
